# This file was generated by GoReleaser. DO NOT EDIT.
cask "codegraph" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "6a9640f66645f0f62aac786904105c8fecc8f7ee9624404839f5c4c334af39fb"
      url "https://github.com/seanb4t/codegraph-go/releases/download/v#{version}/codegraph_v#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "023e3a33b7e5ca442e62817b44cf84f87e9cb646502a2791e373e35383f6b6e2"
      url "https://github.com/seanb4t/codegraph-go/releases/download/v#{version}/codegraph_v#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "efdfa42f001d6e73d08353e23d022f7fadc7fc16d91eaf6f316c1599d5dcae3a"
      url "https://github.com/seanb4t/codegraph-go/releases/download/v#{version}/codegraph_v#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "7cae1b4f867d2c2603881db0ca44db75f8f9659a996b7b7e33f4ec2503f0f872"
      url "https://github.com/seanb4t/codegraph-go/releases/download/v#{version}/codegraph_v#{version}_linux_arm64.zip"
    end
  end

  name "codegraph"
  desc "Pre-indexed code knowledge graph for coding agents"
  homepage "https://github.com/seanb4t/codegraph-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codegraph"

  postflight do
    # D-10: the install itself is BREW-05's gate. system_command's
    # default is must_succeed: true (Homebrew's SystemCommand.run!),
    # and Cask::Installer#install_artifacts does not rescue that
    # failure — it rolls back and re-raises (installer.rb:330-354:
    # "rescue => e ... ensure purge_versioned_files; raise e"), so
    # `brew install` exits non-zero for the first user whose binary
    # cannot even run `man` or reports the wrong version.
    # generate_completions_from_executable below CANNOT play this
    # role: Cask::Artifact::GeneratedCompletion#write_completion
    # (generated_completion.rb:138-148) wraps its own execution of
    # the binary in `rescue => e; opoo e` — a warning, not a raise
    # (RESEARCH.md Pitfall 1; measured directly by this repo's own
    # perturbation in Taskfile.yml's release:rehearse-cask, which
    # deliberately breaks that stanza and observes a green exit).
    # This hook — and only this hook — is BREW-05's gate.
    binary = "#{HOMEBREW_PREFIX}/bin/codegraph"
    man_dir = "#{HOMEBREW_PREFIX}/share/man/man1"

    # UF-5 fix (review cycles 1-2): a per-path freshness BASELINE,
    # not a wall-clock guess. A "one second before the hook started"
    # oracle carries a one-second window in which a page written by
    # a PREVIOUS run counts as fresh, and it is additionally
    # sensitive to filesystem timestamp precision and to clock
    # adjustment; a before/after snapshot of the exact
    # `codegraph*.1` set has no wall-clock slack at all. Records
    # BOTH mtime AND size per path — mtime alone cannot detect a
    # same-tick rewrite (see the residual note below the freshness
    # check). Missing pages are simply absent from the Hash — their
    # absence is what makes a newly-created page detectable.
    man_pages_before = Dir.glob("#{man_dir}/codegraph*.1").each_with_object({}) do |p, h|
      h[p] = { mtime: File.mtime(p), size: File.size(p) }
    end

    # Assertion one (D-11): the man generation produced something.
    # Reads the directory rather than trusting the exit status alone
    # — a binary that ran and wrote nothing would otherwise pass
    # vacuously (repo rule 84d1gfpywd). No specific count is
    # pinned: the page tree grows with every new subcommand, and a
    # pinned count would turn that growth into a broken install.
    system_command binary, args: ["man", man_dir]
    man_pages = Dir.glob("#{man_dir}/codegraph*.1")
    if man_pages.length <= 1
      raise "codegraph cask post-install: expected more than 1 man page under #{man_dir}, found #{man_pages.length}"
    end

    # Assertion one-and-a-half, UF-5 (T-04-05): the pages this run
    # produced are actually FRESH, not residue from a prior failed
    # install (03-EVIDENCE.md:815-833 measured 30 such orphans —
    # Homebrew's rollback purges the Caskroom but never runs the
    # uninstall hook that would have cleaned this shared directory).
    # A page is fresh when it is absent from man_pages_before (newly
    # created by this run), its mtime advanced past the baseline
    # (rewritten by this run), or its size differs from the baseline
    # (rewritten within the same timestamp tick — the
    # coarse-granularity case, only detectable because the baseline
    # also recorded size). Freshness rather than growth is
    # deliberate and load-bearing: a `brew reinstall` rewrites the
    # SAME pages, so a count-grew assertion would break Step 5d's
    # idempotency rehearsal, while this comparison passes on
    # reinstall (rewritten pages advance past their own baseline)
    # and still fails the case UF-5 named: a binary that ran, exited
    # 0, and wrote nothing over a directory of residue.
    #
    # Residual, stated rather than hidden: if a filesystem's mtime
    # granularity is coarse enough that a rewrite within the same
    # tick leaves the mtime byte-identical AND the rewritten content
    # happens to be the same length, a pure-rewrite reinstall could
    # read as not-fresh — a rewrite byte-identical in both length
    # and timestamp is indistinguishable from no rewrite at all, and
    # no metadata comparison can close that. The rehearsal's
    # independent `find -newer` probe against a real marker file
    # (Taskfile.yml's release:rehearse-cask) is the second,
    # independent check of the same property.
    fresh_man_pages = man_pages.select do |p|
      before = man_pages_before[p]
      before.nil? || File.mtime(p) > before[:mtime] || File.size(p) != before[:size]
    end
    if fresh_man_pages.empty?
      raise "codegraph cask post-install: 0 of #{man_pages.length} codegraph*.1 page(s) under #{man_dir} are fresh (before=#{man_pages_before.length}, total=#{man_pages.length}, fresh=#{fresh_man_pages.length}) — the binary ran but produced no new or rewritten man pages"
    end

    # Assertion two (D-11): it is the right artifact. Equality on
    # values normalized by stripping a single leading "v" — never
    # containment, since "0.8.0" is contained in both "0.8.01" and
    # "10.8.0". `version` here is the Ruby DSL delegate (the cask's
    # OWN declared version, base/dsl/base.rb:25's def_delegators),
    # not a Go identifier.
    version_result = system_command binary, args: ["version", "--json"]
    reported_version = JSON.parse(version_result.stdout)["version"].to_s.sub(/\Av/, "")
    declared_version = version.to_s.sub(/\Av/, "")
    if reported_version != declared_version
      raise "codegraph cask post-install: installed binary reports version #{reported_version.inspect}, cask declares #{declared_version.inspect}"
    end

    # Idempotency: every step above tolerates re-running over an
    # existing install. `codegraph man`'s own os.MkdirAll is
    # create-if-absent and doc.GenManTree overwrites each page — and
    # a `brew reinstall` rewriting those pages is exactly the case
    # the freshness assertion above is designed to still pass: each
    # rewritten page's mtime (or size, for a same-tick rewrite)
    # advances past its own baseline. Homebrew re-runs this hook on
    # both reinstall and upgrade.
  end
  generate_completions_from_executable "codegraph",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  uninstall_postflight do
    # D-07: symmetric with post.install — brew does not track files
    # a hook writes, so they must be removed explicitly, via an
    # explicit statement rather than a chained `&&` list. The
    # declarative `uninstall: delete:`/`zap: trash:` stanzas were
    # rejected: these are artifacts THIS CASK generated, not user
    # data. Force-style removal (no error on an already-absent
    # file) because the man pages may legitimately already be gone
    # (e.g. a prior manual cleanup).
    man_dir = Pathname.new("#{HOMEBREW_PREFIX}/share/man/man1")
    Dir.glob((man_dir/"codegraph*.1").to_s).each { |f| FileUtils.rm_f(f) }
  end

  # No zap stanza required

end
