# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "0.16.1"

  on_macos do
    on_arm do
      sha256 "dfa8cf13184137f8ede49394908e8cedd87a7a9ecc7bdaeb1d4d458a10daf68d"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9ce2b5f91578881a3937f94359033312ec5e5c29c26dac31cc4b7ffe495e5cc"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e6cf721e2247d839d787c93b44fe14ae0c9239113e338a57c8224caece48d5ab"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77010db164b48e7fb3ae4d93fd34496e7775bb75bc207840755d3676b547a5a0"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
  end

  name "engram"
  desc "Self-hosted, correctable, OAuth-secured memory for coding agents"
  homepage "https://github.com/seanb4t/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    # engram ships unsigned (CGO_ENABLED=0, no GoReleaser Pro and no
    # Apple Developer Program membership). Invoking the binary before
    # stripping quarantine gets it SIGKILLed by Gatekeeper instead of
    # failing cleanly with a diagnosable message, so the strip must be
    # the literal first statement in this hook. xattr does not exist on
    # Linux, which has no Gatekeeper quarantine to strip in the first
    # place, so this is guarded to macOS only.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end

    # This runs after Homebrew's install_artifacts has already created
    # the HOMEBREW_PREFIX symlink, so the installed binary (not the
    # staged archive) is what gets exercised here. system_command
    # defaults to must_succeed: true, so a non-zero exit from the
    # binary raises on its own; the explicit raise below covers the
    # case where the binary exits zero but reports the wrong version.
    # No v-prefix normalization on either side: engram's version string
    # and archive names are bare SemVer with no "v" prefix already, so
    # both sides are already in the same shape.
    binary = "#{HOMEBREW_PREFIX}/bin/engram"
    result = system_command binary, args: ["version", "--output", "json"]
    reported_version = JSON.parse(result.stdout)["version"].to_s
    declared_version = version.to_s
    if reported_version != declared_version
      raise "engram cask post-install: installed binary reports version " \
            "#{reported_version.inspect}, cask declares #{declared_version.inspect}"
    end

    # Completions are written from the installed binary via
    # system_command (which raises on failure), never via the
    # declarative completions: field and never via Homebrew's
    # completion-generation helper — that helper's write_completion
    # wraps execution in a rescue that downgrades a failure to a
    # warning, so a broken binary would install green. The helper is
    # named neither here nor anywhere else in this file on purpose:
    # the acceptance gate for this decision is a literal occurrence
    # count over this file, so naming it even in a comment destroys
    # the gate's ability to tell prose from actual use.
    # This is the second time the hook exercises the binary, which is
    # the point: a binary that cannot produce completions is a binary
    # that fails the install rather than one that installs with a
    # warning.
    {
      "bash" => "#{HOMEBREW_PREFIX}/etc/bash_completion.d/engram",
      "zsh" => "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_engram",
      "fish" => "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/engram.fish",
    }.each do |shell, dest|
      completion = system_command binary, args: ["completion", shell]
      FileUtils.mkdir_p(File.dirname(dest))
      File.write(dest, completion.stdout)
    end
  end

  uninstall_postflight do
    # Homebrew tracks only the files IT installs, never files a hook
    # wrote, so without this an uninstall leaves all three completion
    # files behind. Removes exactly those three paths — never their
    # parent directories, which are shared with other formulae and
    # casks — with the file-scoped remover, never the recursive tree
    # remover.
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/etc/bash_completion.d/engram"
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_engram"
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/engram.fish"
  end

  # No zap stanza required
end
