# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "0.18.0"

  on_macos do
    on_arm do
      sha256 "b25cefeb24b3511d28fd7a09e7bc995757f1a8d425ccdaeaf08be2f4b770235d"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "76d29922344b9d66c23ce9b63fa443acf6d64a036b6c0500d5f3f4763ef2b07d"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1aebefc6e95c78b8c3c0488b91f51b05e7d89a6cf5bef8357fb7aa213dd63fd0"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2873a540715db27652bfd614c0f9ae2c30751063eca10750aeaf85d40e3335f4"
      url "https://github.com/seanb4t/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
  end

  name "engram"
  desc "Self-hosted, correctable, OAuth-secured memory for coding agents"
  homepage "https://github.com/seanb4t/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    # engram ships unsigned (CGO_ENABLED=0, no GoReleaser Pro and no
    # Apple Developer Program membership). Invoking the binary before
    # stripping quarantine gets it SIGKILLed by Gatekeeper instead of
    # failing cleanly with a diagnosable message, so the strip must be
    # the literal first statement in this hook. xattr does not exist on
    # Linux, which has no Gatekeeper quarantine to strip in the first
    # place, so this is guarded to macOS only.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end

    # This runs after Homebrew's install_artifacts has already created
    # the HOMEBREW_PREFIX symlink, so the installed binary (not the
    # staged archive) is what gets exercised here. system_command
    # defaults to must_succeed: true, so a non-zero exit from the
    # binary raises on its own; the explicit raise below covers the
    # case where the binary exits zero but reports the wrong version.
    # No v-prefix normalization on either side: engram's version string
    # and archive names are bare SemVer with no "v" prefix already, so
    # both sides are already in the same shape.
    binary = "#{HOMEBREW_PREFIX}/bin/engram"
    result = system_command binary, args: ["version", "--output", "json"]
    reported_version = JSON.parse(result.stdout)["version"].to_s
    declared_version = version.to_s
    if reported_version != declared_version
      raise "engram cask post-install: installed binary reports version " \
            "#{reported_version.inspect}, cask declares #{declared_version.inspect}"
    end

    # Completions are written from the installed binary via
    # system_command (which raises on failure), never via the
    # declarative completions: field and never via Homebrew's
    # completion-generation helper — that helper's write_completion
    # wraps execution in a rescue that downgrades a failure to a
    # warning, so a broken binary would install green. The helper is
    # named neither here nor anywhere else in this file on purpose:
    # the acceptance gate for this decision is a literal occurrence
    # count over this file, so naming it even in a comment destroys
    # the gate's ability to tell prose from actual use.
    # This is the second time the hook exercises the binary, which is
    # the point: a binary that cannot produce completions is a binary
    # that fails the install rather than one that installs with a
    # warning.
    {
      "bash" => "#{HOMEBREW_PREFIX}/etc/bash_completion.d/engram",
      "zsh" => "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_engram",
      "fish" => "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/engram.fish",
    }.each do |shell, dest|
      completion = system_command binary, args: ["completion", shell]
      FileUtils.mkdir_p(File.dirname(dest))
      File.write(dest, completion.stdout)
    end

    # This is the hook's fourth exercise of the installed binary
    # (after the quarantine strip, the version gate, and the
    # completions loop above): the binary writes one roff man page
    # per available command straight into the shared man1 directory
    # below. system_command's default must_succeed (true) raises if
    # the binary cannot document itself, exactly as it already does
    # for a broken version report or a failed completion write.
    # Homebrew's own declarative field for installing man pages is
    # not used, for the same rescue-to-warning reason the
    # completions loop above avoids its own declarative alternative
    # and helper — neither is named here, or anywhere else in this
    # file, on purpose: the acceptance gate for this decision is a
    # literal occurrence count over the whole file, so naming either
    # even in a comment would destroy the gate's ability to tell
    # prose from actual use.
    man1_dir = "#{HOMEBREW_PREFIX}/share/man/man1"
    FileUtils.mkdir_p(man1_dir)
    system_command binary, args: ["man", man1_dir]
  end

  uninstall_postflight do
    # Homebrew tracks only the files IT installs, never files a hook
    # wrote, so without this an uninstall leaves the completion
    # files (and, below, the generated man pages) behind. Removes
    # exactly the paths the install hook wrote — never their parent
    # directories, which are shared with other formulae and casks —
    # with the file-scoped remover, never the recursive tree
    # remover.
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/etc/bash_completion.d/engram"
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_engram"
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/engram.fish"

    # The pages the install hook wrote above are removed by globbing
    # exactly engram.1 and engram-*.1 under man1 and applying the
    # same file-scoped remover to each match — never the directory,
    # which is shared with other formulae and casks, and never a
    # recursive remover. There is no install-time manifest: the
    # binary symlink is already gone by the time this hook runs, so
    # the page set cannot be regenerated here to diff against.
    Dir.glob("#{HOMEBREW_PREFIX}/share/man/man1/engram{,-*}.1").each { |f| FileUtils.rm_f f }
  end

  # No zap stanza required
end
